### ISSUE TITLE
Line

### ISSUE THREAD

**Issue by bertaviader** [stufisher/freeboard-flot-extended#1]
How it work the x-axis time? I don't know how to put the time. Furthermore, when I make a push in my api, the other values disappaer.

Thanks!

**Comment by stufisher** [comment]
You need to pass your x axis in seconds*1000 (javascript uses milliseconds). This plugin doesnt use a FIFO like https://github.com/tecywiz121/freeboard-flot plugin. You need to return all your data from the api, primarily for historical data.
